spring:
    application:
        name: Todo
    datasource:
        url: jdbc:postgresql://localhost:5432/tasks_notes
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format-sql: true
    server:
        port: 8989